### ISSUE TITLE
C version?

### ISSUE THREAD

**Issue by alec-jensen** [codeaye/minesweeper#3]
Since rust sucks, can we get a version written in a good language, like C?

**Comment by codeaye** [comment]
No, c got deprecated boss

**Comment by alec-jensen** [comment]
> No, c got deprecated boss

Since when

**Comment by codeaye** [comment]
yesterday morning boss, the c repository segfaulted

**Comment by alec-jensen** [comment]
I don't see this anywhere, what is your source?

**Comment by codeaye** [comment]
trust me bro

**Comment by codeaye** [comment]
alr i gotta sleep il talk later
